#!/bin/bash

syncthing --version

cd ~/Download/

curl -s https://api.github.com/repos/syncthing/syncthing/releases/latest | grep browser_download_url | grep linux-amd64 | cut -d '"' -f 4 | wget -qi - 

tar xf syncthing-linux-amd64*.tar.gz
echo "Unziped"

sudo cp syncthing-linux-amd64-*/syncthing  /usr/local/bin/

rm -R syncthing*
echo "Cleaned"

syncthing --version